# The URL the site will be built for
base_url = "https://bytesnake.github.io/blog"

title = "Notes and Tones"

description = "Blog and personal site of Lorenz Schmidt."

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# We are using the anpu theme here
theme = "anpu"

taxonomies = [
    { name = "categories" },
    { name = "tags" },
    { name = "ingredients" },
]

ignored_content = ["*/arbeitsbuch/*.md", "*/sport/*.md"]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL", name = "Posts" },
    { url = "$BASE_URL/about/me", name = "About Me" },
]

social = [
    { url = "https://zettel.haus/@losch", image = "mastodon.svg"},
    { url = "https://github.com/bytesnake", image = "github.svg"},
]
